ROOT_DIR=~steve/nasa/seastar/seastarhq/data/SeaSTAR-20250711-Ames_roof-general_suntracking
SCRIPTS_DIR=$ROOT_DIR/L0.6/scripts
L05_DATA_DIR=$ROOT_DIR/pickle
RAW_DATA_DIR=$ROOT_DIR/raw_csv
EXTRACTED_DATA_DIR=$ROOT_DIR/L0.6/extracted_txt
PLOTS_DIR=$ROOT_DIR/L0.6/plots
L06_DATA_DIR=$ROOT_DIR/pickle
PICKLE_DIR=$ROOT_DIR/pickle

export ROOT_DIR SCRIPTS_DIR L05_DATA_DIR RAW_DATA_DIR EXTRACTED_DATA_DIR PLOTS_DIR PICKLE_DIR L06_DATA_DIR
