ROOT_DIR=~steve/nasa/seastar/seastarhq/data/SeaSTAR-20250710-Ames_roof-general_suntracking/
SCRIPTS_DIR=$ROOT_DIR/L0.5/scripts
RAW_DATA_DIR=$ROOT_DIR/raw_csv
EXTRACTED_DATA_DIR=$ROOT_DIR/L0.5/extracted_txt
PLOTS_DIR=$ROOT_DIR/L0.5/plots
PICKLE_DIR=$ROOT_DIR/L0.5/pickle

export ROOT_DIR SCRIPTS_DIR RAW_DATA_DIR EXTRACTED_DATA_DIR PLOTS_DIR PICKLE_DIR
