SEASTAR_TIMEZONE="US/Pacific"

AVG_INTERVAL=1
ANALYSIS_MARGIN=0.25

HOT_BLOCK1_MIN=39
HOT_BLOCK1_MAX=41

HOT_BLOCK2_MIN=39
HOT_BLOCK2_MAX=41

COLD_BLOCK_MIN=20
COLD_BLOCK_MAX=22

WATER_MIN=30
WATER_MAX=35

BRIGHTNESS_MIN=160
BRIGHTNESS_MAX=195
TRACKING_EUCLIDIAN_MAX=0.05

IMU_TEMP_MAX=50
IMU_TEMP_MIN=40
IMU_PRESS_MIN=800
IMU_PRESS_MAX=1100

TRIPLETVAR_TOLERANCE_PERCENT=2
TRIPLETVAR_TIME=10

TEMP_TRIPLET_TIME=10
TEMP_SLOPE_TOLERANCE=0.003  # slope of degrees C per timestep
WINDOWWIDTH=10   # moving average window width for 
TEMP_D2TDT2_TOLERANCE=0.2  # second derivate of degrees C per timestep

TEMP_CORR_BASELINE=39.5
TEMP_CORR_SCALEFACTOR=0.00464


export SEASTAR_TIMEZONE
export AVG_INTERVAL ANALYSIS_MARGIN 
export HOT_BLOCK1_MIN HOT_BLOCK1_MAX
export HOT_BLOCK2_MIN HOT_BLOCK2_MAX
export COLD_BLOCK_MIN COLD_BLOCK_MAX
export WATER_MIN WATER_MAX
export BRIGHTNESS_MIN BRIGHTNESS_MAX
export TRACKING_EUCLIDIAN_MAX
export IMU_TEMP_MAX IMU_TEMP_MIN
export IMU_PRESS_MAX IMU_PRESS_MIN
export TRIPLETVAR_TOLERANCE_PERCENT
export TRIPLETVAR_TIME
export TEMP_TRIPLET_TIME
export TEMP_SLOPE_TOLERANCE
export WINDOWWIDTH
export TEMP_D2TDT2_TOLERANCE
export TEMP_CORR_BASELINE
export TEMP_CORR_SCALEFACTOR
