SEASTAR_TIMEZONE="US/Pacific"

AVG_INTERVAL=1
ANALYSIS_MARGIN=0.25

HOT_BLOCK1_MIN=39
HOT_BLOCK1_MAX=41

HOT_BLOCK2_MIN=39
HOT_BLOCK2_MAX=41

COLD_BLOCK_MIN=20
COLD_BLOCK_MAX=22

WATER_MIN=30
WATER_MAX=35

BRIGHTNESS_MIN=160
BRIGHTNESS_MAX=195
TRACKING_EUCLIDIAN_MAX=0.05

IMU_TEMP_MAX=50
IMU_TEMP_MIN=40
IMU_PRESS_MIN=800
IMU_PRESS_MAX=1100

TRIPLETVAR_TOLERANCE_PERCENT=2
TRIPLETVAR_TIME=10


export SEASTAR_TIMEZONE
export AVG_INTERVAL ANALYSIS_MARGIN 
export HOT_BLOCK1_MIN HOT_BLOCK1_MAX
export HOT_BLOCK2_MIN HOT_BLOCK2_MAX
export COLD_BLOCK_MIN COLD_BLOCK_MAX
export WATER_MIN WATER_MAX
export BRIGHTNESS_MIN BRIGHTNESS_MAX
export TRACKING_EUCLIDIAN_MAX
export IMU_TEMP_MAX IMU_TEMP_MIN
export IMU_PRESS_MAX IMU_PRESS_MIN
export TRIPLETVAR_TOLERANCE_PERCENT
export TRIPLETVAR_TIME
