ROOT_DIR=/home/steve/nothing/seastar/seastarhq/data/SeaSTAR-20260914-SLO-general_suntracking
SCRIPTS_DIR=$ROOT_DIR/L0.6/scripts
RAW_DATA_DIR=$ROOT_DIR/raw
EXTRACTED_DATA_DIR=$ROOT_DIR/L0.6/extracted_txt
PLOTS_DIR=$ROOT_DIR/L0.6/plots
L06_DATA_DIR=$ROOT_DIR/pickle
SEASTAR_TIMEZONE=null
AVG_INTERVAL=1
ANALYSIS_MARGIN=0.25

export ROOT_DIR SCRIPTS_DIR RAW_DATA_DIR EXTRACTED_DATA_DIR PLOTS_DIR L06_DATA_DIR SEASTAR_TIMEZONE AVG_INTERVAL ANALYSIS_MARGIN
