ROOT_DIR=/home/steve/nothing/seastar/seastarhq/data/SeaSTAR-20260914-SLO-general_suntracking
SCRIPTS_DIR=$ROOT_DIR/L1.0/scripts
L05_DATA_DIR=$ROOT_DIR/pickle
RAW_DATA_DIR=$ROOT_DIR/raw
EXTRACTED_DATA_DIR=$ROOT_DIR/L1.0/extracted_txt
PLOTS_DIR=$ROOT_DIR/L1.0/plots
L06_DATA_DIR=$ROOT_DIR/pickle
L10_DATA_DIR=$ROOT_DIR/pickle
PICKLE_DIR=$ROOT_DIR/pickle

export ROOT_DIR SCRIPTS_DIR L05_DATA_DIR RAW_DATA_DIR EXTRACTED_DATA_DIR PLOTS_DIR PICKLE_DIR L06_DATA_DIR L10_DATA_DIR
